version: "3.9"

services:
    db:
        image: mysql
        container_name: db_php
        restart: on-failure
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    phpmyadmin:
        image: phpmyadmin
        container_name: phpMyAdmin_cours_php
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8005:80
        environment:
            PMA_HOST: db

    web:
        build: php
        restart: on-failure
        container_name: cours_php
        volumes:
            - ./app:/app:rw
        ports:
            - 8085:80

volumes:
    db-data: null
